🐎 ci: Update release CI

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -14,6 +14,7 @@ jobs:
     outputs:
       release_id: ${{fromJson(steps.create-release.outputs.result).id}}
       release_url: ${{fromJson(steps.create-release.outputs.result).html_url}}
+      release_version: ${{steps.get-version.outputs.PACKAGE_VERSION}}
     steps:
       - uses: actions/checkout@v4
       - name: Setup node
@@ -21,7 +22,11 @@ jobs:
         with:
           node-version: lts/*
       - name: Get version
-        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
+        id: get-version
+        run: |
+          PACKAGE_VERSION=$(node -p "require('./package.json').version")
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
+          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
       - name: Create release draft
         id: create-release
         uses: actions/github-script@v7
@@ -42,7 +47,7 @@ jobs:
           RELEASE_URL: ${{fromJson(steps.create-release.outputs.result).html_url}}
         run: |
           echo "Release url: $RELEASE_URL"
-  build-release:
+  build-desktop-release:
     needs: create-release
     permissions:
       contents: write
@@ -106,3 +111,115 @@ jobs:
           RELEASE_URL: ${{needs.create-release.outputs.release_url}}
         run: |
           echo "Release url: $RELEASE_URL"
+  build-android-release:
+    needs: create-release
+    permissions:
+      contents: write
+    runs-on: ubuntu-22.04
+    environment: Release
+    env:
+      RELEASE_ID: ${{needs.create-release.outputs.release_id}}
+      RELEASE_VERSION: ${{needs.create-release.outputs.release_version}}
+      JAVA_DISTRIBUTION: 'adopt'
+      JAVA_VERSION: 17
+      NDK_VERSION: 27.1.12297006
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
+      - name: Setup Bun
+        uses: oven-sh/setup-bun@v2
+        with:
+          bun-version: latest
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: ${{env.JAVA_DISTRIBUTION}}
+          java-version: ${{env.JAVA_VERSION}}
+          cache: gradle
+      - name: Setup Android SDK
+        uses: android-actions/setup-android@v3
+      - name: Install NDK
+        run: |
+          sdkmanager "ndk;$NDK_VERSION"
+          echo "NDK_HOME=$ANDROID_HOME/ndk/$NDK_VERSION" >> $GITHUB_ENV
+      - name: Install Rust stable
+        uses: dtolnay/rust-toolchain@stable
+        with:
+          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android
+      - name: Rust cache
+        uses: swatinem/rust-cache@v2
+        with:
+          workspaces: "./src-tauri -> target"
+      - name: Install frontend dependencies
+        run: bun install --frozen-lockfile
+      - name: Setup Android signing
+        run: |
+          ANDROID_DIRECTORY=src-tauri/gen/android
+          echo "${{secrets.ANDROID_KEY_BASE64}}" | base64 -d > $RUNNER_TEMP/keystore.jks
+          echo "keyAlias=${{secrets.ANDROID_KEY_ALIAS}}" > $ANDROID_DIRECTORY/keystore.properties
+          echo "password=${{secrets.ANDROID_KEY_PASSWORD}}" >> $ANDROID_DIRECTORY/keystore.properties
+          echo "storeFile=$RUNNER_TEMP/keystore.jks" >> $ANDROID_DIRECTORY/keystore.properties
+      - name: Build Android APK per abi
+        run: |
+            bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json --apk --split-per-abi
+      - name: Rename APKs and move to temp directory
+        run: |
+          for apk in $(find . -type f -name "*.apk"); do
+            echo "Found APK: $apk"
+            filename=$(basename $apk)
+            directory=$(dirname $apk)
+            arch=$(echo $filename | cut -d'-' -f2)
+            new_filename=Vultr.Firewall.Watcher_$RELEASE_VERSION_$arch.apk
+            mv $apk $RUNNER_TEMP/$new_filename
+            echo "Renamed APK: $RUNNER_TEMP/$new_filename"
+          done
+      - name: Build Android bundle
+        run: |
+          bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json --apk
+      - name: Rename APKs
+        run: |
+          APK_PATH=src-tauri/gen/android/app/build/outputs/apk
+          mv $APK_PATH/arm/release/app-arm-release.apk $APK_PATH/arm/release/$RELEASE_VERSION-arm-32.apk
+          mv $APK_PATH/arm64/release/app-arm64-release.apk $APK_PATH/arm64/release/$RELEASE_VERSION-arm64.apk
+      - name: Rename universal APK and aab
+        run: |
+          output_dir=src-tauri/gen/android/app/build/outputs
+          universal_apk_path=$output_dir/apk/universal/release/app-universal-release.apk
+          if [ ! -f $universal_apk_path ]; then
+            echo "Universal APK not found at $universal_apk_path"
+            exit 1
+          fi
+          echo "Found universal APK: $universal_apk_path"
+          mv $universal_apk_path $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.apk
+          echo "Renamed universal APK: $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.apk"
+
+          universal_aab_path=$output_dir/bundle/universalRelease/app-universal-release.aab
+          if [ ! -f $universal_aab_path ]; then
+            echo "Universal AAB not found at $universal_aab_path"
+            exit 1
+          fi
+          echo "Found universal AAB: $universal_aab_path"
+          mv $universal_aab_path $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.aab
+          echo "Renamed universal AAB: $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.aab"
+      - name: Upload artifacts to release asset
+        uses: actions/github-script@v7
+        with:
+          script: |
+            const fs = require('fs');
+            const path = require('path');
+            const version = process.env.RELEASE_VERSION;
+            const files = fs.readdirSync(process.env.RUNNER_TEMP).filter(file => file.startsWith(`Vultr.Firewall.Watcher_${version}`));
+            for (const file of files) {
+              console.log(`Uploading ${file}...`);
+              const { data } = await github.rest.repos.uploadReleaseAsset({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                release_id: process.env.RELEASE_ID,
+                name: file,
+                data: fs.createReadStream(path.join(process.env.RUNNER_TEMP, file))
+              });
+            }
+            console.log('All files uploaded.');
+          
+      
+      
