🐎 ci: Add rename artifacts step in test build CI

diff --git a/.github/workflows/test-build.yml b/.github/workflows/test-build.yml
--- a/.github/workflows/test-build.yml
+++ b/.github/workflows/test-build.yml
@@ -124,9 +124,41 @@ jobs:
           echo "keyAlias=$KEY_ALIAS" > $ANDROID_DIRECTORY/keystore.properties
           echo "password=$STORE_PASS" >> $ANDROID_DIRECTORY/keystore.properties
           echo "storeFile=$RUNNER_TEMP/$STORE_FILE" >> $ANDROID_DIRECTORY/keystore.properties
-      - name: Build Android bundle
-        run: |
-          bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json
       - name: Build Android APK per abi
         run: |
           bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json --apk --split-per-abi
+      - name: Rename APKs and move to temp directory
+        run: |
+          for apk in $(find . -type f -name "*.apk"); do
+            echo "Found APK: $apk"
+            filename=$(basename $apk)
+            directory=$(dirname $apk)
+            arch=$(echo $filename | cut -d'-' -f2)
+            new_filename=Vultr.Firewall.Watcher_$RELEASE_VERSION_$arch.apk
+            mv $apk $RUNNER_TEMP/$new_filename
+            echo "Renamed APK: $RUNNER_TEMP/$new_filename"
+          done
+      - name: Build Android bundle and move to temp directory
+        run: |
+          bun run tauri android build -v --config src-tauri/build-config/tauri.android.conf.json
+      - name: Rename universal APK and aab
+        run: |
+          output_dir=src-tauri/gen/android/app/build/outputs
+          universal_apk_path=$output_dir/apk/universal/release/app-universal-release.apk
+          if [ ! -f $universal_apk_path ]; then
+            echo "Universal APK not found at $universal_apk_path"
+            exit 1
+          fi
+          echo "Found universal APK: $universal_apk_path"
+          mv $universal_apk_path $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.apk
+          echo "Renamed universal APK: $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.apk"
+
+          universal_aab_path=$output_dir/bundle/universalRelease/app-universal-release.aab
+          if [ ! -f $universal_aab_path ]; then
+            echo "Universal AAB not found at $universal_aab_path"
+            exit 1
+          fi
+          echo "Found universal AAB: $universal_aab_path"
+          mv $universal_aab_path $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.aab
+          echo "Renamed universal AAB: $RUNNER_TEMP/Vultr.Firewall.Watcher_$RELEASE_VERSION_universal.aab"
+      
